version: '3.8'
name: your-project-name

services:
  database:
    container_name: your-project-name-database
    restart: unless-stopped
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '5306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - your-project-name

  app:
    container_name: your-project-name-app
    restart: unless-stopped
    build:
      context: php
    volumes:
      - ./app:/var/www/app
    depends_on:
      - database
    networks:
      - your-project-name

  nginx:
    container_name: your-project-name-nginx
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database
    networks:
      - your-project-name

networks:
  your-project-name:
    driver: bridge
